### PR TITLE
using latest sdk versions.

### LINKED ISSUE #22: https://www.bing.com/shop?&entrypoint=edgemmx&PC=EMMX01
@

### PR DESCRIPTION
**Pull request by AndroidDeveloperLB**
using latest sdk versions.
using SparseArray instead of HashMap
using switch-case for strings when possible

### CODE REVIEW

**Comment by jaredrummler** [comment]
Sorry, but since the code messes with the code/style (indentation) I won't merge this.

**Comment by AndroidDeveloperLB** [comment]
Send me your settings of styles, and I will re-format each file. I'm pretty sure I used the default formatting.

**Comment by AndroidDeveloperLB** [comment]
Please do send. I worked on this for quite a while to impove it for Android, and formatting code is a matter of seconds...

**Comment by jaredrummler** [comment]
I made the change to SparseArray and updated to the latest build tools and appcompat version. Using a switch-case has no affect on performance.

**Comment by AndroidDeveloperLB** [comment]
Actually, switch-case on strings could be faster in performance, at least on JVM :
http://stackoverflow.com/questions/22110707/how-is-string-in-switch-statement-more-efficient-than-corresponding-if-else-stat
https://javarevisited.blogspot.com/2014/05/how-string-in-switch-works-in-java-7.html
http://java-performance.info/string-switch-performance/

Not sure if this is optimized on Android, but it sure is nicer to see such code instead of a lot of if-else conditions.

**Pull request closed without merging**
